### ISSUE TITLE
wcc broken on linux when quotes are used

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#1172]
```
$ cat test.c
#include <stdio.h>

$ cat Makefile.os2
CFLAGS = -I"$(%WATCOM)/h/os2" -I"$(%WATCOM)/h" -zq
SRCS = test.c
OBJS = $(SRCS:.c=.obj)

.extensions:
.extensions: .lib .dll .obj .c .asm

all: test.obj

.c.obj:
    wcc386 $(CFLAGS) -fo=$^@ $<

$ wmake -f Makefile.os2
Open Watcom Make Version 2.0 beta Dec 20 2023 01:31:16 (32-bit)
Copyright (c) 2002-2023 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See https://github.com/open-watcom/open-watcom-v2#readme for details.
	wcc386 -I"/tmp/watcom/h/os2" -I"/tmp/watcom/h" -zq -fo=test.obj test.c
Open Watcom C x86 32-bit Optimizing Compiler
Version 2.0 beta Dec 20 2023 01:33:31 (32-bit)
Copyright (c) 2002-2023 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See https://github.com/open-watcom/open-watcom-v2#readme for details.
Error! E1139: Command line contains more than one file to compile
Error! E1139: Command line contains more than one file to compile
test.c(1): Error! E1055: Unable to open 'stdio.h'
Error(E42): Last command making (test.obj) returned a bad status
Error(E02): Make execution terminated
```

The one working I have is the build from 30 November: Don't know which
commit broke it.

Using quotes like above is important for the same makefile to work under
both windows and linux. However with the current ow build, it only works
under windows: that is not desirable or acceptable.

**Comment by sezero** [comment]
OK, I tried replacing wmake with the one from Nov.30 build or ow1.9:
it still errors out the same way. It looks like the issue is elsewhere?

**Comment by sezero** [comment]
Hm, I kept everything intact in the latest build, but I replaced wcc386
with the one from Nov.30 build: it successfully completes the build..

**Comment by sezero** [comment]
I _think_ (but not exactly sure) that the issue started with https://github.com/open-watcom/open-watcom-v2/commit/806a88c3c756bcda5984a60f451ff57d630152c5 with its follow-up commits up to https://github.com/open-watcom/open-watcom-v2/commit/6ea175f2edea73b87a64159b5e36cf9edc1af2b1

**Comment by jmalak** [comment]
I think, it should be fixed.
The reason it didn't show up is because of a second build issue that was broken by a bug in wasm. The last normal build is for the buggy version. Once wasm is patched, the OW build process updates the OW build to the patched version.

**Comment by joncampbell123** [comment]
Ah, I was just about to report this having hit this myself last night. DOSLIB's hw/dosboxid library is unbuildable with the latest because it thinks iglib.c is more than one file to compile. :)

**Comment by sezero** [comment]
> because it thinks iglib.c is more than one file to compile. :)

:joy: :joy: :joy: 

I first thought that wmake was the culprit (the error message tricked me), but it's actually in the compiler..

**Comment by sezero** [comment]
> I think, it should be fixed. The reason it didn't show up is because of a second build issue that was broken by a bug in wasm. The last normal build is for the buggy version. Once wasm is patched, the OW build process updates the OW build to the patched version.

Which commit fixed it??? The build I last tested is from https://github.com/open-watcom/open-watcom-v2/commit/92b6bcab2944d6d16cd99d2d554f32767ce0915c

**Comment by joncampbell123** [comment]
> > because it thinks iglib.c is more than one file to compile. :)
> 
> 😂 😂 😂
> 
> I first thought that wmake was the culprit (the error message tricked me), but it's actually in the compiler..

It took me awhile to track it down to quoting because it would complain about multiple files, then complain that it couldn't find the stdio.h header included by iglib.c, and then complain about too many error messages. Wut? :laughing:

**Comment by jmalak** [comment]
I just fixed wasm that now OW should be build again.
It should create fixed C compiler.

**Comment by sezero** [comment]
Well, the CI build logs of latest commit (2380387176b0092c982131c8b0c3d4284fc160a3) show that the assembler fails similar to what is described here, e.g.:
```
bwasm -q -D_BLDVER=1300 -D_CYEAR=2023  -we -d1 -DNDEBUG -fo=msgseg.obj -w8-cx -bt=os2        -I"../../../bld/hdr/dos/h" -I"../../../bld/os2api/os2286/h"  -I"../../../bld/watcom/h" ../lib286/msgseg.asm
Open Watcom x86 Assembler Version 2.0 beta Dec 21 2023 22:11:52 (64-bit)
Copyright (c) 2002-2023 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1992-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See https://github.com/open-watcom/open-watcom-v2#readme for details.
Error: Command Line Contains More Than 1 File To Assemble 
Error(E42): Last command making (msgseg.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed
Error: Process completed with exit code 1.
```

I will try whenever a new CI-build is available, though..

**Comment by jmalak** [comment]
Sorry, my stupid mistake in wasm command line macro definition processing.
I add it as new function OPT_GET_OPTION to command line scanner.

**Comment by joncampbell123** [comment]
Almost there!

win386/dll fails with "FIDRQQ" and "FIWRQQ" is an undefined reference on my Linux system when building from source.

**Comment by jmalak** [comment]
You need to rebuild from scratch, because most of libraries are damaged by previous wasm bug.

**Comment by joncampbell123** [comment]
I did a:

    git clean -dfx
    git reset --hard
    ./build.sh

Still fails as before, "FIDRQQ" and "FIWRQQ" is an undefined reference in bld/win386/dll

**Comment by jmalak** [comment]
No, this bug affected also in-line assembler.
I hope that I fixed now all places where FPU instruction emulation flag is used.

**Comment by joncampbell123** [comment]
That fixed it, thanks! :+1:

**Comment by joncampbell123** [comment]
doslib builds but iglib.c still throws an error about multiple files.

Here's the execve() command on Linux that shows exactly what wcc was given on the command line. What in the command line here looks like multiple C source files?

    execve("/usr/src/open-watcom-v2-upstream/rel/binl/wcc", ["wcc", "-fr=nul", "-fo=win300l/iglib.obj", "-i..", "-i../..", "-e=2", "-zq", "-zu", "-zw", "-ml", "-d0", "-s", "-nt=_TEXT", "-bt=windows", "-oilrb", "-os", "-wx", "-0", "-dTARGET_MSDOS=16", "-dTARGET_WINDOWS=30", "-dMSDOS=1", "-dTARGET86=86", "-DMMODE=l", "-q", "-x", "-i/usr/src/open-watcom-v2-upstream/rel/h;/usr/src/open-watcom-v2-upstream/rel/h/win", "-D_WINDOWS_16_", "-bg", "iglib.c"], 0xab3008 /* 30 vars */) = 0

**Comment by jmalak** [comment]
I think you use too old buggy version of compiler.

**Comment by joncampbell123** [comment]
> I think you use too old buggy version of compiler.

This is how wcc was invoked for iglib.c using Open Watcom from your latest commit. It's not clear to me how wcc invoked in that manner constitutes "multiple files". The failure to find stdio.h is a strange side effect it seems.

**Comment by sezero** [comment]
It still fails. Failure differs on how I invoke the compiler.
Using the latest CI build extracted to `/tmp/watcom`:

(1) If I specify watcompaths, etc on the command line, it fails like this:
```
$ WATCOM=/tmp/watcom PATH=/tmp/watcom/binl:$PATH wmake -f Makefile.os2
$ cat 1a
Open Watcom Make Version 2.0 beta Dec 22 2023 02:09:08 (32-bit)
Copyright (c) 2002-2023 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See https://github.com/open-watcom/open-watcom-v2#readme for details.
	wcc386 -zq -bt=os2 -bm -fp5 -fpi87 -mf -oeatxh -w4 -ei -zp8 -wcd=303 -5s -I"/tmp/watcom/h/os2" -I"/tmp/watcom/h" -DHAVE_FNMATCH -DHAVE_MKSTEMP -DHAVE_UMASK -Iinclude -bd -DBUILDING_DLL -fo=src/virtual.obj src/virtual.c
Open Watcom C x86 32-bit Optimizing Compiler
Version 2.0 beta Dec 22 2023 02:11:31 (32-bit)
Copyright (c) 2002-2023 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See https://github.com/open-watcom/open-watcom-v2#readme for details.
Error! E1139: Command line contains more than one file to compile
Error! E1139: Command line contains more than one file to compile
src/common.h(15): Error! E1055: Unable to open 'stdarg.h'
src/common.h(16): Error! E1055: Unable to open 'limits.h'
src/common.h(17): Error! E1055: Unable to open 'stdlib.h'
src/common.h(18): Error! E1055: Unable to open 'stdio.h'
src/common.h(19): Error! E1055: Unable to open 'string.h'
src/common.h(243): Error! E1127: Type required in parameter list
src/common.h(243): Error! E1127: Type required in parameter list
src/common.h(244): Error! E1127: Type required in parameter list
src/common.h(551): Error! E1009: Expecting ',' but found '*'
src/common.h(551): Error! E1116: An id list not allowed except for function definition
src/common.h(552): Error! E1009: Expecting ',' but found '*'
src/common.h(552): Error! E1116: An id list not allowed except for function definition
src/common.h(553): Error! E1009: Expecting ',' but found '*'
src/common.h(553): Error! E1116: An id list not allowed except for function definition
src/common.h(554): Error! E1009: Expecting ',' but found '*'
src/common.h(554): Error! E1116: An id list not allowed except for function definition
src/common.h(555): Error! E1009: Expecting ',' but found '*'
src/common.h(555): Error! E1116: An id list not allowed except for function definition
src/common.h(556): Error! E1147: Too many errors: compilation aborted
Error(E42): Last command making (src/virtual.obj) returned a bad status
Error(E02): Make execution terminated
```

(2) If I create a shell script for invoking watcom stuff, then it fails like this:
```
$ $ cat owtest.sh
#!/bin/sh

export WATCOM=/tmp/watcom
export PATH=$WATCOM/binl:$PATH
export INCLUDE=$WATCOM/h/os2:$WATCOM/h

exec "$@"
```
```
$ ./owtest.sh wmake -f Makefile.os2
Open Watcom Make Version 2.0 beta Dec 22 2023 02:09:08 (32-bit)
Copyright (c) 2002-2023 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See https://github.com/open-watcom/open-watcom-v2#readme for details.
	wcc386 -zq -bt=os2 -bm -fp5 -fpi87 -mf -oeatxh -w4 -ei -zp8 -wcd=303 -5s -I"/tmp/watcom/h/os2" -I"/tmp/watcom/h" -DHAVE_FNMATCH -DHAVE_MKSTEMP -DHAVE_UMASK -Iinclude -bd -DBUILDING_DLL -fo=src/virtual.obj src/virtual.c
Open Watcom C x86 32-bit Optimizing Compiler
Version 2.0 beta Dec 22 2023 02:11:31 (32-bit)
Copyright (c) 2002-2023 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See https://github.com/open-watcom/open-watcom-v2#readme for details.
Error! E1139: Command line contains more than one file to compile
Error! E1139: Command line contains more than one file to compile
Error(E42): Last command making (src/virtual.obj) returned a bad status
Error(E02): Make execution terminated
```

**Comment by jmalak** [comment]
I see, it looks like mistake in some option processing.
I improve diagnostics to show what option caused this message exactly.
OW build works properly because it doesn't use "wrong" option.
Anyway I will fix it ASAP.

**Comment by sezero** [comment]
Tested the Last CI build from https://github.com/open-watcom/open-watcom-v2/commit/822086a6fd61d3c92399d2ec9aca6205c51f9f33, the issue seems fixed (tested only on linux), thanks.

Feel free to close this ticket if there aren't anything else to do at your end.

**Comment by jmalak** [comment]
Good news, Thanks.
