### ISSUE TITLE
Resource compiler crashing regularly

### ISSUE THREAD

**Issue by ArmstrongJ** [open-watcom/open-watcom-v2#213]
I've noticed that in fresh build lately, `wrc` is crashing when compiling resources for Windows NT.  The crash occurs on both NT and Linux builds of wrc, so it isn't limited to one host.  The error seems to be attempting to read a null pointer:

```
wrc ..\main.rc -bt=nt -dWIN32 -d_WIN32 -d__NT__ -i="C:\Users\Jeffrey\Workspace\sfortran\fwin\;C:\Watcom/h;C:\Watcom/h/nt" -q -ad -r -fo=main.res
The instruction at 0x0067d977 referenced memory at 0x00000000.The memory could not be read.Exception fielded by 0x00403780EAX=0x00000000 EBX=0x00000001 ECX=0x00000006 EDX=0x00000006ESI=0x0085c0f7 EDI=0x0085c11b EBP=0x0085c0f7 ESP=0x0019fa54EIP=0x0067d977 EFL=0x00010246 CS =0x00000023 SS =0x0000002bDS =0x0000002b ES =0x0000002b FS =0x00000053 GS =0x0000002bStack dump (SS:ESP)0x00000006 0x008a2b45 0x0085c11b 0x0085c0f7 0x00000006 0x0067d83f 0xffff0001 0x10c002c2 0x0000000b 0x0000003d 0x0019fabc 0x0085c0f5 0x0066e68c 0x00058b68 0x008401f9 0x00000000 0x008b0eb5 0x00001020 0x00840091 0x00870000 0x00280014 0x0085c0f5 0x008700d2 0x00658210 0x00280014 0x008700d2 0x0085c0f5 0x008a2b45 0x00000000 0x00870000 0x0000003d 0x008a2b45 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x0066b6e7 0x00000000 0x0000000f 0x008b0e15 0x00300038 0x35343533 0x00000036 0x00000008 0x0000000b 0x00000042 0x0019fb78 0x0019fb3c 0x00000000 0x00000000 0x0066b768 0x0019f
b78 0x0019fb78 0x00000004 0x0000000b 0x00000004 0x0019fb78 0x00000004 0x00000000 0x00659736 0x0019fb00 0x00668a00 0x004090a0 0x01eb00b2 0x00000001 0x00668a50 0x0068ff24 Error(E14): Cannot execute (wrc): No error
Error(E42): Last command making (C:\Users\Jeffrey\Workspace\sfortran\fwin\watcom\main.res) returned a bad status
Error(E02): Make execution terminated
```

**Comment by jmalak** [comment]
Please is it possible to get all source file for main.rc?

**Comment by ArmstrongJ** [comment]
I'll put together a simplified case (the offending source file can't be distributed).

**Comment by jmalak** [comment]
Probably it is fixed by various fixes

**Comment by revelator** [comment]
Unfortunatly this one is still a problem, i get a similar crash just trying to run it.
The code seems to cache FILE pointers, but somewhere something is passing a NULL pointer into res_seek 
causing the C runtime to to trigger an exception.

**Comment by jmalak** [comment]
It should b fixed by 82512d5bf07d5a26e02a70d6616a9bbb9a992ca9 commit

**Comment by revelator** [comment]
Yep works fine now.
