### ISSUE TITLE
Linux installer crashes with segmentation fault when terminal type is rxvt-unicode-256color

### ISSUE THREAD

**Issue by ackalker** [open-watcom/open-watcom-v2#216]
I've downloaded the Linux installer from http://sourceforge.net/projects/openwatcom/files/current-build/open-watcom-2_0-c-linux-x86/download .
When I run it, it clears the screen, then crashes with a segmentation fault:

``` bash
$ ./open-watcom-2_0-c-linux-x86
Segmentation fault (core dumped)
```

I'm running Arch Linux x86_64, with the [multilib] repository enabled.

With some digging and a lot of luck, I found that the installer doesn't seem to like the specific terminal I'm using (urxvt):

``` bash
$ echo $TERM
rxvt-unicode-256color
```

When I force the terminal type to be `linux`, everything works fine:

``` bash
$ TERM=linux ./open-watcom-2_0-c-linux-x86
```

Perhaps this problem has long since been fixed, the installer binaries on SourceForge are rather old.

**Comment by jmalak** [comment]
In OW is basic support for common terminal type as xterm, linux, ansi, ...
If you want to support your terminal type then somebody must add support for your terminal.

**Comment by tidux** [comment]
That's going to be a hard blocker for any usefulness on Linux in the future considering that every GNU/Linux distro worth the name has defaulted to UTF-8 for the past decade.

**Comment by jmalak** [comment]
Yes, it is not only installer problem. OW use subproject UI for full-screen text console interface. This part of code is used by any fullscreen oriented application. I am not much familiare with this part. Any help is welcome.

**Comment by jmalak** [comment]
I hope it is resolved by latest submit, see #225

**Comment by tidux** [comment]
Not fixed.  Search path needs to include /usr/share/terminfo/*/ as well to conform with modern standard Linux paths.  This whole Linux port feels very shoddy.

```
ls /usr/share/terminfo  
1/  3/  5/  7/  9/  A/  c/  e/  f/  h/  j/  l/  m/  n/  o/  P/  Q/  s/  u/  w/  X/
2/  4/  6/  8/  a/  b/  d/  E/  g/  i/  k/  L/  M/  N/  p/  q/  r/  t/  v/  x/  z/
```

**Comment by jmalak** [comment]
It should be working this way, subdirectoty is derived from terminal type name first character.

**Comment by tidux** [comment]
Travis master build dumps core/stacktrace under TERM=screen-256color

On April 29, 2018 5:29:52 PM PDT, "Jiří Malák" <notifications@github.com> wrote:
>It should be working this way, subdirectoty is derived from terminal
>type name first character.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/open-watcom/open-watcom-v2/issues/216#issuecomment-385294415

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jmalak** [comment]
Please, what application?

**Comment by tidux** [comment]
binl64/vi on Debian 9 amd64
