### ISSUE TITLE
bogus W200 warning

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#479]
```
$ cat 0.c

typedef struct {
    float x, y, z, w;
    float s, t;
    float r, g, b, a;
} TlVertex3D;
typedef float TlMatrix[4][4];

#define VP_OFFSET 1.0f
#define VP_SCALE  0.5f

void tlProjectVertices( TlVertex3D *dstVerts, const TlVertex3D *srcVerts, unsigned length )
{
    TlVertex3D tmp, v;
    TlMatrix m;
    unsigned i;

    m[0][0] = 1.0f, m[0][1] = 0.0f, m[0][2] = 0.0f, m[0][3] = 0.0f;
    m[1][0] = 0.0f, m[1][1] = 1.0f, m[1][2] = 0.0f, m[1][3] = 0.0f;
    m[2][0] = 0.0f, m[2][1] = 0.0f, m[2][2] = 1.0f, m[2][3] = 1.0f;
    m[3][0] = 0.0f, m[3][1] = 0.0f, m[3][2] = 0.0f, m[3][3] = 0.0f;

    for( i = 0; i < length; i++ ) {
        v = srcVerts[i];
        tmp = v;
        tmp.x = v.x * m[0][0] + v.y * m[1][0] + v.z * m[2][0] + v.w * m[3][0];
        tmp.y = v.x * m[0][1] + v.y * m[1][1] + v.z * m[2][1] + v.w * m[3][1];
        tmp.z = v.x * m[0][2] + v.y * m[1][2] + v.z * m[2][2] + v.w * m[3][2];
        tmp.w = v.x * m[0][3] + v.y * m[1][3] + v.z * m[2][3] + v.w * m[3][3];
        tmp.x /= tmp.w, tmp.y /= tmp.w, tmp.z /= tmp.w;
        tmp.x += VP_OFFSET, tmp.x *= VP_SCALE;
        tmp.y += VP_OFFSET, tmp.y *= VP_SCALE;
        dstVerts[i] = tmp;
    }
}
```

Code is from 3dfx glide source.  Compiling it emits the following warning:

```
$ wcc386 -wx -zq -ox -5s -fo=0.o 0.c
0.c(15): Warning! W200: 'm' has been referenced but never assigned a value
```

Unless I am missing something, this is bogus.  Gcc does not warn.

**Comment by jmalak** [comment]
Thanks for bug report. It is fixed in git repository now.

**Comment by sezero** [comment]
@jmalak:  Thanks for fixing the bogus warning.

However: If you comment out the initialization of m[] array, there are
_no warnings_ now, where there _must_ be.  I do not know whether
this is a side effect of the fix.

**Comment by jmalak** [comment]
I will check and fix it.

**Comment by jmalak** [comment]
it is fixed now by 3ded97db356e8bfe3b12a0d75f1bb42473d42b83 commit
It was very old bug comming from WATCOM 11 source which was now visible.
My first fix removed code which masked this bug.
There was problem with optimized array index that it was not properly identified as array during setup symbol assigned flag.

**Comment by sezero** [comment]
Thank you my friend.

Unfortunately, the travis master build still doesn't warn for me,
but your commit has a 'x' for travis, so I guess travis builds does
not yet reflect the latest change.

**Comment by jmalak** [comment]
Sorry, I did mistake and Travis build failed.
I fix my mistake by d36cec97a2ea11f6f0a3c060041afa57548a9058 commit
Travis build should finish after 1.5 hour.

**Comment by ewe2** [comment]
This is popping up for me in rel build for commit c2919da0e while compiling owl
```
==== 08:42:27 /home/ewe2/devel/openwatcom/watcom/bld/owl/nt386.dll ====
cc owfile.obj
/home/ewe2/devel/openwatcom/watcom/bld/owl/c/owfile.c(170): Warning! W200: 'buffer' has been referenced but never assigned a value
Error(E42): Last command making (owfile.obj) returned a bad status
Error(E02): Make execution terminated
<pmake -d build          -h> => non-zero return: 512
Build failed
```

**Comment by sezero** [comment]
> `/home/ewe2/devel/openwatcom/watcom/bld/owl/c/owfile.c(170): Warning! W200: 'buffer' has been referenced but never assigned a value`

Another bogus W200..

**Comment by jmalak** [comment]
I am working on fix, but it requires more changes in C compiler.
In the meantime I disable diagnose for arrays.

**Comment by jmalak** [comment]
The problem is in OW C and C++ compilers how it identify unreferenced and uninitialized variable/array.
it is very simple algorithm which is suitable for variable or pointer, but for array it doesn't work properly.
It will require to rework code to work properly with arrays. Until it will rework, reporting is switch off as before to prevent false positive warning.

**Comment by samizzo** [comment]
I noticed that the compiler also doesn't pick up references if the only assignment to the variable is in an asm block. For example:

```
void foo(void)
{
    int bar;
    __asm
    {
        mov bar, 3
    }
    printf("%i\n", bar);
}
```

I guess this case might not be an easy fix.

**Comment by jmalak** [comment]
Thanks for bug report.
Generaly it need develop some procedure to identify if any element of array were changed.
It is hard if pointer to array is passed indirectly, because reference to array doesn't mean any value change.

**Comment by jmalak** [comment]
#1158
