### ISSUE TITLE
Spurious "Unprototyped function" warnings?

### ISSUE THREAD

**Issue by ArmstrongJ** [open-watcom/open-watcom-v2#566]
Using a build from last night, I'm seeing a shocking number of "Unprototyped function" warnings showing up during a build.  For example, here are two warnings about calls that are defined in the same file before the call is made:

```
..\html.c(506): Warning! W308: Unprototyped function 'PopulateHTMLRecent' called
..\html.c(506): Note! I2002: 'PopulateHTMLRecent' defined in: ..\html.c(484)
..\html.c(512): Warning! W308: Unprototyped function 'PopulateHTMLTemplates' called
..\html.c(512): Note! I2002: 'PopulateHTMLTemplates' defined in: ..\html.c(469)
```

I'm seeing this warning with functions prototyped properly in header files (the compiler even says where) as well.

I'm not sure when this issue was introduced.

**Comment by jmalak** [comment]
It is strange. It looks like you use old code base. Messages 
ERR_PARM_NOT_REFERENCED				303
ERR_NONPROTO_FUNC_CALLED			308
ERR_NONPROTO_FUNC_CALLED_INDIRECT	309
were enabled by default for C compiler, but OW code base was fixed before.
On my build servers (64-bit hosts) I didn't get any problem.
What host compiler and platform you are using?

**Comment by ArmstrongJ** [comment]
The build server is running OW 1.9 32-bit on 64-bit Linux host.  These results were running the 32-bit compiler from this build on Windows 10.

I'll check to make sure 'git pull' properly finished when building the OW distro...

**Comment by jmalak** [comment]
OK. I will try to build OW by latest build OW compiler in similar configuration.

**Comment by jmalak** [comment]
I didn't get any problem.
Do you have still problem or it was fixed by source code update?

**Comment by ArmstrongJ** [comment]
I'm still seeing it on a build from last night.  Not sure what's happening...

The builds are available at http://buildbot.approximatrix.com/releases/

and the build output is available http://buildbot.approximatrix.com/builders/global_build_rel/builds/2071/steps/Global%20Build

**Comment by jmalak** [comment]
i will check your logs thanks for links

**Comment by jmalak** [comment]
Could you give me sample of your source file with all warnings/errors.

**Comment by jmalak** [comment]
This message can be confusing, it looks like prototype is missing.
But it is output also if parameters are not declared in prototype and efectively some parameters are used (old K&R).

**Comment by samizzo** [comment]
I'm seeing these warnings as well and I can't see any unused parameters. For an example, the attached two files compiled with the following exhibits this:

```set wcc386=-fpi87 -fp5 -j -5r -zro -mf -wcd=106 -dPLATFORM_DOS   -bt=dos4g -I=u_smp11b\src -dDEBUG -wx -d2 -fr=DOS\DEBUG\random.err -ad=DOS\DEBUG\random.d -fo=DOS\DEBUG\random.obj
	wcc386 src\random.c```

[random.h.txt](https://github.com/open-watcom/open-watcom-v2/files/3826890/random.h.txt)
[random.c.txt](https://github.com/open-watcom/open-watcom-v2/files/3826891/random.c.txt)

**Comment by samizzo** [comment]
Ahh, my bad, if I put `void` in the parameter list for no param functions it clears it up.

**Comment by jmalak** [comment]
It is message required by standard (it diagnose obsolete K&R declaration), they were completely disabled in the past due to unfixed OW code base. Now code is more portable that I enable them by default. Unfortunately it diagnose all code if Warning level is 3 and above.
It is possible to move these messages to Warning level 4 (-wx). Default Warning level is 1.
It looks like that this type of mistake is frequent that I could relax fn() as fn( void ) if possible as OW extension.

**Comment by samizzo** [comment]
No problem! I see that actually technically the prototype should have `void` in there anyway so I've gone and fixed up all my code to be correct.

**Comment by jmalak** [comment]
I changed message 308 and 309 text to be more transparent.
Now they are.
308 The function '%s' without prototyped parameters called
309 The function without prototyped parameters indirectly called

**Comment by jmalak** [comment]
I relaxed the case as I described before, because it is still valid even if it is deprecated and not recomended for future standard direction.

**Comment by ArmstrongJ** [comment]
I'm not seeing the warnings anymore.  I think I understand the warnings more based on this discussion.  I certainly don't add `(void)` for functions that don't take arguments.  I guess that was the issue.  Can we close this?

**Comment by jmalak** [comment]
I think we can close it now.

I relaxed declaration of function without parameters to be int fn(); or int fn(void);
But int fn() declaration and call fn( param ) will report problem with undeclared parameters.
Also message was fixed to be more readable 
`The function '%s' without prototyped parameters called`
